### ISSUE TITLE
python3 scripts/regression.py report  , extract are broken

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/Surelog#3187]
python3 scripts/regression.py report
....
Comparing StringMethod
Comparing StringParameter
Comparing BlackParrotMuteErrors
Comparing ArianeElab2
Comparing BlackParrotParam

Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 1195, in <module>
    sys.exit(_main())
  File "/home/alain/Surelog/scripts/regression.py", line 1179, in _main
    result = _report(args, filtered_tests)
  File "/home/alain/Surelog/scripts/regression.py", line 954, in _report
    summary = _print_report(results)
  File "/home/alain/Surelog/scripts/regression.py", line 851, in _print_report
    summary['MAX CPU TIME'] = f'{round(longest_cpu_test["CPU-TIME"], 2)} ({longest_cpu_test["TESTNAME"]})'
KeyError: 'CPU-TIME'

**Comment by alaindargelas** [comment]
~/Surelog$ python3 scripts/regression.py  extract
Starting Surelog Regression Tests @ 2022-08-28 13:51:22.572343
Environment:
      command-line: scripts/regression.py extract
   current-dirpath: /home/alain/Surelog
 workspace-dirpath: /home/alain/Surelog
     build-dirpath: /home/alain/Surelog/build
  surelog-filepath: /home/alain/Surelog/build/bin/surelog
uhdm-dump-filepath: /home/alain/Surelog/build/third_party/UHDM/bin/uhdm-dump
roundtrip-filepath: /home/alain/Surelog/build/bin/roundtrip
     test-dirpaths: /home/alain/Surelog/tests; /home/alain/Surelog/third_party/tests
    output-dirpath: /home/alain/Surelog/build/regression
   multi-threading: None
  multi-processing: None
          max-jobs: 16
         max-tests: 619
 blacklisted-tests: 7
    filtered-tests: 612



Extracting 612 test logs ...
Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 1195, in <module>
    sys.exit(_main())
  File "/home/alain/Surelog/scripts/regression.py", line 1185, in _main
    result = _extract(args, filtered_tests)
  File "/home/alain/Surelog/scripts/regression.py", line 1039, in _extract
    raise "Missing required archive path"
TypeError: exceptions must derive from BaseException

**Comment by alaindargelas** [comment]
Thanks
